'use strict';

const state = {cases: [], products: [], page: 'inbox', selected: null, tab: 'resolve', filter: 'All', search: '', busy: false, dirty: false, actors: [], approvalEnabled: false, actor: sessionStorage.getItem('qf-demo-actor') || 'admin'};
const $ = (selector) => document.querySelector(selector);
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = name => `<i data-lucide="${name}" aria-hidden="true"></i>`;
const fmt = value => Number(value).toLocaleString('en-SG', {minimumFractionDigits:2, maximumFractionDigits:2});
const current = () => state.cases.find(c => c.id === state.selected);
const samples = [
  {title:'Routine maintenance order', recipient:'Acme purchasing team', text:'50 EL-MCB-1P16\n20 BX-IP65-2015-A', name:'Standard order', description:'Two catalogue items, available from stock.', icon:'clipboard-check'},
  {title:'Junction boxes for Jurong', recipient:'Acme purchasing team', text:'20 IP65 junction boxes 200 x 150 mm', name:'Product clarification', description:'A material choice before pricing.', icon:'messages-square'},
  {title:'Lighting replacement', recipient:'Acme purchasing team', text:'80 LT-PNL-36W-4K with another 20 percent discount', name:'Commercial exception', description:'Split delivery and a discount approval.', icon:'git-pull-request'}
];

async function api(path, method='GET', payload) {
  const response = await fetch(path, {method, headers:{'Content-Type':'application/json', 'X-Demo-Actor':state.actor}, ...(payload ? {body:JSON.stringify(payload)} : {})});
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Request failed.');
  return data;
}
function icons(){ if(window.lucide) window.lucide.createIcons(); }
function renderPersona(){
  const actor=state.actors.find(a=>a.id===state.actor);
  const label=document.createElement('label');
  label.className='persona-picker';
  label.innerHTML=`Demo persona<select id="persona" aria-label="Demo persona">${state.actors.map(a=>`<option value="${a.id}" ${a.id===state.actor?'selected':''}>${esc(a.name)}</option>`).join('')}</select>`;
  $('.topbar .right').prepend(label);
  const profile=$('.profile');
  if(profile)profile.innerHTML=`<div class="avatar">${state.actor==='admin'?'DA':state.actor==='manager'?'SM':'FA'}</div><div><strong class="small">${esc(actor?.role||'Demo persona')}</strong><div class="small">Simulated identity</div></div>`;
  if(state.actor!=='admin')document.querySelectorAll('[data-action="new"],[data-action="sample"],[data-action="save-lines"],[data-action="add-line"],[data-action="remove-line"],[data-action="save-recipient"],[data-action="consent"],[data-action="review"],[data-action="delete"],.line-item input,.line-item select,#recipient,#delivery-consent').forEach(el=>el.disabled=true);
}
async function showHistory(){
  const history=state.approvalEnabled?await api(`/api/cases/${current().id}/revisions`):{revisions:[]};
  const dialog=$('#history-dialog');
  dialog.innerHTML=`<div class="dialog-head"><h2 id="history-title">Revision history</h2><button class="icon-button quiet" data-action="close-dialog" title="Close">${icon('x')}</button></div><h3>Saved revision inputs</h3>${history.revisions.slice().reverse().map(r=>`<details class="revision-snapshot"><summary>Revision ${r.revision} · ${r.lines.length} lines</summary><p class="small">Recipient: ${esc(r.recipient)}<br>Split delivery: ${r.delivery_accepted?'accepted':'not accepted'}</p>${r.lines.map(l=>`<p class="small">${esc(l.qty)} ${esc(l.uom||'')} · ${esc(l.sku||'Unresolved product')} · Extra ${esc(l.discretionary_percent||0)}%</p>`).join('')}</details>`).join('')}<h3>Decisions & events</h3><div class="timeline">${current().history.slice().reverse().map(h=>`<div class="event"><strong>${esc(h.action)}</strong><span class="small">Revision ${h.revision} · ${esc(h.actor||'legacy demo operator')} · ${new Date(h.time).toLocaleString()}</span></div>`).join('')}</div>`;
  dialog.showModal();icons();
}
function toast(message){ $('#toast').textContent=message; $('#toast').classList.add('visible'); clearTimeout(window.toastTimer); window.toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000); }
function badge(status){ const tone = status === 'Needs clarification' || status === 'Awaiting approval' || status === 'Changes requested' ? 'warn' : status === 'Ready for review' ? 'blue' : ''; return `<span class="badge ${tone}">${icon(status==='Reviewed'?'check':'circle-dot')}${esc(status)}</span>`; }
function discard(){ if(state.dirty && !confirm('Discard unsaved line changes?')) return false; state.dirty=false; return true; }
function replaceCase(item){ const i=state.cases.findIndex(c=>c.id===item.id); if(i<0) state.cases.unshift(item); else state.cases[i]=item; state.dirty=false; }
function stats(){ const counts=[['All enquiries',state.cases.length,'inbox','Saved locally'],['Needs attention',state.cases.filter(c=>['Needs clarification','Awaiting approval','Changes requested'].includes(c.status)).length,'flag','Open exceptions'],['Ready for review',state.cases.filter(c=>c.status==='Ready for review').length,'file-check-2','Prepared drafts'],['Reviewed',state.cases.filter(c=>c.reviewed).length,'circle-check','Not externally sent']]; return `<div class="stats">${counts.map(([label,n,i,note])=>`<div class="stat"><div class="stat-label">${label}${icon(i)}</div><strong>${n.toString().padStart(2,'0')}</strong><span class="small">${note}</span></div>`).join('')}</div>`; }
function render(){
  $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">${icon('workflow')}QuoteFlow</div><div><div class="workspace-label">Sales workspace</div><nav class="nav"><button data-action="nav" data-page="inbox" class="${state.page!=='dashboard'?'active':''}">${icon('inbox')}<span>Enquiries</span><b class="count">${state.cases.length}</b></button><button data-action="nav" data-page="dashboard" class="${state.page==='dashboard'?'active':''}">${icon('chart-no-axes-combined')}<span>Overview</span></button></nav></div><div class="sidebar-foot"><div class="small"><span class="status-dot"></span>Offline demo</div><div class="small">Synthetic catalogue · SGD</div><div class="profile"><div class="avatar">LO</div><div><strong class="small">Local operator</strong><div class="small">Single-user sandbox</div></div></div></div></aside><main class="main"><header class="topbar"><span>Workspace &nbsp; / &nbsp; ${state.page==='case'?'Quotations':state.page==='dashboard'?'Overview':'Enquiries'}</span><div class="right"><span class="offline"><span class="status-dot"></span>Local demo</span><span>Fixture date: 17 Sep 2026</span></div></header><div class="content">${state.page==='case'&&current()?caseView():state.page==='dashboard'?dashboard():inbox()}<footer class="footer-note">Synthetic demo · Frozen catalogue: 17 Sep 2026 · No paid AI calls or external sending</footer></div></main></div>`;
  renderPersona();
  icons();
}
function inbox(){
  return `<div class="page-title"><div><h1>Enquiries</h1><p class="muted">Your quotation queue, from request to review.</p></div><button class="primary" data-action="new">${icon('plus')}New enquiry</button></div>${stats()}<div class="toolbar"><div class="filters">${['All','Needs clarification','Awaiting approval','Changes requested','Ready for review','Reviewed'].map(f=>`<button data-action="filter" data-filter="${f}" class="${state.filter===f?'selected':''}">${f==='All'?'All enquiries':f}</button>`).join('')}</div><label class="search">${icon('search')}<input id="search" placeholder="Search enquiries" aria-label="Search enquiries" value="${esc(state.search)}"></label></div><div id="case-table">${caseTable()}</div><section class="samples"><div class="section-head"><h2>Sample enquiries</h2><span class="small">Synthetic inputs</span></div><div class="sample-grid">${samples.map((s,i)=>`<button class="sample" data-action="sample" data-index="${i}">${icon(s.icon)}<span><strong>${s.name}</strong><small>${s.description}</small></span>${icon('arrow-up-right')}</button>`).join('')}</div></section>`;
}
function caseTable(){
  const cases=state.cases.filter(c=>(state.filter==='All'||c.status===state.filter)&&`${c.id} ${c.title} Acme Facilities`.toLowerCase().includes(state.search.toLowerCase()));
  if(!cases.length) return `<div class="empty">${icon(state.cases.length?'search-x':'inbox')}<h3>${state.cases.length?'No matching enquiries':'Your queue is clear'}</h3><p>${state.cases.length?'Try another status or search.':'Create an enquiry or choose a sample below.'}</p>${!state.cases.length?'<button data-action="new">New enquiry</button>':''}</div>`;
  return `<div class="table-wrap"><table><thead><tr><th>Enquiry</th><th>Customer</th><th>Status</th><th>Lines</th><th>Total SGD</th><th></th></tr></thead><tbody>${cases.map(c=>`<tr class="case-row" data-action="open" data-id="${c.id}"><td><strong>${esc(c.title)}</strong><span class="muted">${c.id} · Rev ${c.revision}</span></td><td><strong>Acme Facilities</strong><span class="muted">Gold · Net 30</span></td><td>${badge(c.status)}</td><td>${c.lines.length.toString().padStart(2,'0')}</td><td>${c.evaluation.blocks.length?'—':fmt(c.evaluation.total)}</td><td><button class="icon-button quiet" data-action="open" data-id="${c.id}" title="Open enquiry">${icon('arrow-right')}</button></td></tr>`).join('')}</tbody></table></div><div class="row-foot"><span>${cases.length} ${cases.length===1?'enquiry':'enquiries'}</span><span>SGD · Totals include mock GST</span></div>`;
}
function dashboard(){ return `<div class="page-title"><div><h1>Overview</h1><p class="muted">Current activity in your local workspace.</p></div><button data-action="refresh" title="Refresh">${icon('refresh-cw')}</button></div>${stats()}<h2>Queue by status</h2><div class="metric-lines">${['Needs clarification','Awaiting approval','Changes requested','Ready for review','Reviewed'].map(s=>`<div class="metric-line"><span>${badge(s)}</span><button class="quiet" data-action="queue" data-filter="${s}">${state.cases.filter(c=>c.status===s).length} ${icon('arrow-right')}</button></div>`).join('')}</div><h2>Runtime</h2><div class="metric-lines"><div class="metric-line"><span>Live model calls</span><strong>Disabled · 0 calls</strong></div><div class="metric-line"><span>Model spend</span><strong>USD 0.00</strong></div><div class="metric-line"><span>Shared account balance</span><span class="muted">Unverified</span></div><div class="metric-line"><span>Application golden-set evaluation</span><span class="muted">Not run</span></div><div class="metric-line"><span>Measured handling-time baseline</span><span class="muted">Not available</span></div></div>`; }
function sourcePanel(c){ return `<aside class="source-panel"><div class="eyebrow">Original enquiry</div><h3>${esc(c.title)}</h3><p class="small">Acme Facilities Pte Ltd</p><div class="source-text">${esc(c.text)}</div><dl><dt>Recipient</dt><dd>${esc(c.recipient)}</dd><dt>Customer account</dt><dd>CUST-SG-1042</dd><dt>Delivery site</dt><dd>Jurong, Singapore</dd></dl><div class="evidence"><h3>Source records</h3><p>PB-GOLD-SG-2026<br>Catalogue: demo-v1<br>Prices: 17 Sep, 09:00 SGT<br>Inventory: 17 Sep, 09:55 SGT</p></div></aside>`; }
function caseView(){ const c=current(); return `<section class="case-heading"><button class="quiet back" data-action="nav" data-page="inbox">${icon('arrow-left')}All enquiries</button><div class="page-title"><div><h1>${esc(c.title)}</h1><div class="case-meta"><span class="small">${c.id} · Revision ${c.revision}</span>${badge(c.status)}</div></div><div><button class="icon-button" data-action="history" title="Revision history">${icon('history')}</button> <button class="icon-button danger" data-action="delete" title="Delete local case">${icon('trash-2')}</button></div></div><div class="tabs">${[['resolve','list-filter','Resolve'],['price','calculator','Pricing'],['approve','shield-check','Approvals'],['preview','file-text','Preview']].map(([key,i,label])=>`<button data-action="tab" data-tab="${key}" class="${state.tab===key?'active':''}">${icon(i)}${label}</button>`).join('')}</div></section>${state.tab==='preview'?preview(c):`<div class="case-layout">${sourcePanel(c)}<section class="work-panel">${state.tab==='resolve'?resolve(c):state.tab==='price'?pricing(c):approvals(c)}</section></div>`}`; }
function productSpecs(sku){return QuoteFlowSpecifications.render(state.products.find(p=>p.sku===sku));}
function resolve(c){ return `<div class="section-head"><h2>Requested items <span class="muted">(${c.lines.length})</span><span class="badge gray">Catalogue matching</span></h2></div>${c.lines.map((line,i)=>`<div class="line-item" data-line="${i}"><div class="line-editor"><label>Product<select data-field="sku" aria-label="Product line ${i+1}"><option value="">Select product</option>${state.products.map(p=>`<option value="${p.sku}" ${line.sku===p.sku?'selected':''}>${esc(p.name)}${p.active?'':' (discontinued)'}</option>`).join('')}</select></label><label>Quantity<input data-field="qty" type="number" min="1" step="1" aria-label="Quantity line ${i+1}" value="${esc(line.qty)}"></label><label>Unit<select data-field="uom" aria-label="Unit line ${i+1}">${['EA','ROLL','M'].map(u=>`<option ${line.uom===u?'selected':''}>${u}</option>`).join('')}</select></label><label>Extra %<input data-field="discretionary_percent" type="number" min="0" max="100" step="0.01" aria-label="Discount line ${i+1}" value="${esc(line.discretionary_percent||0)}"></label><button class="icon-button quiet" data-action="remove-line" data-index="${i}" title="Remove line ${i+1}" ${c.lines.length===1?'disabled':''}>${icon('x')}</button></div>${!line.sku?`<div class="line-question">${esc(line.question)}</div>`:''}${productSpecs(line.sku)}<div class="line-note">${esc(line.source||'Manually added line')}</div></div>`).join('')}<div class="actionbar"><button data-action="add-line" ${c.lines.length>=20?'disabled':''}>${icon('plus')}Add line</button><button class="primary" data-action="save-lines">${icon('check')}Confirm & calculate</button></div>${c.evaluation.blocks.length?`<div class="notice">${icon('circle-alert')}<div>${c.evaluation.blocks.map(b=>`<p>${esc(b)}</p>`).join('')}</div></div>`:''}<div class="edit-recipient"><label>Recipient name<input id="recipient" value="${esc(c.recipient)}" maxlength="120"></label><button data-action="save-recipient" title="Save recipient">${icon('save')}</button></div>`; }
function totals(e){ return `<div class="totals"><div class="total-row"><span>Subtotal</span><span>${fmt(e.subtotal)}</span></div><div class="total-row"><span>Freight</span><span>0.00</span></div><div class="total-row"><span>Mock GST · 9%</span><span>${fmt(e.tax)}</span></div><div class="total-row grand"><span>Total SGD</span><span>${fmt(e.total)}</span></div></div>`; }
function pricing(c){ const e=c.evaluation; return `<div class="section-head"><h2>Commercial evaluation</h2><span class="small">SGD</span></div>${e.blocks.length?`<div class="notice">${icon('circle-alert')}<div>${e.blocks.map(b=>`<p>${esc(b)}</p>`).join('')}<button data-action="tab" data-tab="resolve">Resolve items</button></div></div>`:''}<div class="table-wrap"><table><thead><tr><th>Product / source</th><th>Qty</th><th>Unit</th><th>Margin</th><th>Amount</th></tr></thead><tbody>${e.lines.map(l=>`<tr><td><strong>${esc(l.sku)}</strong><span class="muted">${l.source_type} · ${fmt(l.source_price)} · ${l.effective_discount}% off</span>${productSpecs(l.sku)}</td><td>${l.qty}</td><td>${l.unit_price}</td><td>${l.margin}%</td><td>${fmt(l.amount)}</td></tr>`).join('')}</tbody></table></div>${totals(e)}${e.stock.length?`<h3>Delivery exception</h3>${e.stock.map(s=>`<div class="stock-row"><strong>${s.sku}</strong><br>${s.now} available on 19 Sep · ${s.later} available on ${s.eta}</div>`).join('')}<label class="check"><input id="delivery-consent" type="checkbox" ${c.delivery_accepted?'checked':''}>Customer explicitly accepted the split quantities and dates above.</label><button data-action="consent">${icon('check')}Record delivery decision</button>`:`<div class="notice good">${icon('package-check')}<p>${e.blocks.length?'Resolve all lines to complete the stock check.':'All priced lines are available from the fixture stock.'}</p></div>`}${e.approvers.length?`<div class="notice">${icon('shield-alert')}<p>Required commercial approval: ${esc(e.approvers.join(' and '))}.</p></div>`:''}<div class="actionbar"><button data-action="tab" data-tab="resolve">${icon('arrow-left')}Edit lines</button><button class="primary" data-action="tab" data-tab="${e.approvers.length?'approve':'preview'}">${e.approvers.length?'View approvals':'Preview quote'}${icon('arrow-right')}</button></div>`; }
function approvals(c) {
  const e=c.evaluation, tasks=c.current_approvals||[], actor=state.actors.find(a=>a.id===state.actor);
  const task=tasks.find(t=>t.role===actor?.role);
  const blocked=e.blocks.length||(e.stock.length&&!c.delivery_accepted);
  return `<h2>Approval requirements</h2><p class="small">Demo simulation · Revision ${c.revision}${state.approvalEnabled?'':' · Approval service unavailable'}</p>
    ${e.approvers.length?`<div class="notice ${c.approval_state==='approved'?'good':''}">${icon(c.approval_state==='approved'?'shield-check':'shield-alert')}<p>${c.approval_state==='approved'?'All required demo approvals recorded.':c.approval_state==='rejected'?'Changes requested. Create a new revision before requesting approval again.':'Each required role must decide this revision before final review.'}</p></div>
    ${e.approvers.map(role=>{const t=tasks.find(x=>x.role===role);return `<div class="stock-row"><strong>${esc(role)}</strong><p class="small">${esc(t?.status||'Not requested')} · Revision ${c.revision}</p>${t?.reason?`<p>${esc(t.reason)}</p><span class="small">${esc(t.decided_by)} · ${esc(new Date(t.decided_at).toLocaleString())}</span>`:''}</div>`;}).join('')}
    ${state.actor==='admin'?`<button data-action="request-approvals" ${!state.approvalEnabled||blocked||tasks.length===e.approvers.length?'disabled':''}>${icon('send')}Request demo approvals</button>`:''}
    ${task?.status==='pending'?`<div class="decision-form"><label>Decision reason<textarea id="decision-reason" maxlength="1000" placeholder="Reason for this decision"></textarea></label><div class="actionbar"><button class="danger" data-action="decision" data-decision="rejected">${icon('x')}Request changes</button><button class="primary" data-action="decision" data-decision="approved">${icon('check')}Approve revision ${c.revision}</button></div></div>`:''}`:
    `<div class="notice good">${icon('shield-check')}<p>No additional commercial approval required.</p></div>`}
    <div class="stock-row"><strong>Sales Administrator review</strong><p class="small">${c.reviewed?'Completed by Demo Administrator':'Pending final review'} · Revision ${c.revision}</p></div>
    <div class="actionbar"><button data-action="tab" data-tab="price">${icon('arrow-left')}Back to pricing</button><button data-action="tab" data-tab="preview">Preview${icon('arrow-right')}</button></div>`;
}
function preview(c){const q=c.quote,e=c.evaluation,blocked=e.blocks.length||(e.stock.length&&!c.delivery_accepted);return `<div class="preview-layout"><article class="paper"><div class="paper-top"><div><div class="eyebrow">${q.draft?'Draft quotation':'Reviewed quotation'}</div><h2>${c.id}</h2><p class="small">Revision ${c.revision} · 17 September 2026</p></div><div class="seller">QuoteFlow Demo Supplies Pte Ltd<p class="small">Singapore · SGD</p></div></div><div class="eyebrow">Prepared for</div><h3>Acme Facilities Pte Ltd</h3><p class="small">Attention: ${esc(c.recipient)}<br>Jurong, Singapore</p>${blocked?`<div class="notice">${icon('circle-alert')}<p>Incomplete draft. Resolve all product and delivery questions before export.</p></div>`:''}<div class="table-wrap"><table><thead><tr><th>Description</th><th>Qty</th><th>Unit SGD</th><th>Amount SGD</th></tr></thead><tbody>${q.lines.map(l=>`<tr><td><strong>${esc(l.name)}</strong><small>${l.sku}</small></td><td>${l.qty} ${l.uom}</td><td>${l.unit_price}</td><td>${fmt(l.amount)}</td></tr>`).join('')}</tbody></table></div>${totals(q)}<h3>Terms & delivery</h3><p class="small">Net 30 · Valid until 24 September 2026.<br>In-stock lines: 19 September 2026. No reservation.</p>${q.delivery.map(s=>`<p class="small">${s.sku}: ${s.now} on 19 Sep; ${s.later} on ${s.eta}. ${c.delivery_accepted?'Split accepted.':'Acceptance pending.'}</p>`).join('')}<p class="small">Synthetic demonstration. Not a commercial offer.</p></article><aside class="preview-side"><div><h3>Review checklist</h3><div class="checklist"><div>${icon('circle-check')}Customer confirmed</div><div>${icon(e.blocks.length?'circle-alert':'circle-check')}Products and calculations</div><div>${icon(e.stock.length&&!c.delivery_accepted?'circle-alert':'circle-check')}Delivery confirmed</div><div>${icon(e.approvers.length&&c.approval_state!=='approved'?'clock':'circle-check')}Commercial approvals</div></div><p class="small">Revision ${c.revision} · ${c.document_hash.slice(0,12)}</p><button class="primary" data-action="review" ${c.reviewed||e.status!=='Ready for review'?'disabled':''}>${icon('check-check')}${c.reviewed?'Reviewed':'Mark reviewed'}</button><button data-action="download" data-format="pdf" ${blocked?'disabled':''}>${icon('download')}Download ${q.draft?'draft ':''}PDF</button><button data-action="download" data-format="email" ${blocked?'disabled':''}>${icon('mail')}Download email draft</button></div><div><h3 class="email-heading">Email draft</h3><div class="email-text">${esc(c.email)}</div></div></aside></div>`;}

function showNew(index){ const s=Number.isInteger(index)?samples[index]:{title:'',recipient:'',text:''}; const dialog=$('#enquiry-dialog'); dialog.innerHTML=`<form id="new-form"><div class="dialog-head"><h2 id="dialog-title">New enquiry</h2><button type="button" class="icon-button quiet" data-action="close-dialog" title="Close">${icon('x')}</button></div><div class="preset-row">${samples.map((x,i)=>`<button type="button" data-action="preset" data-index="${i}">${x.name}</button>`).join('')}</div><div class="form-fields"><label>Subject<input name="title" maxlength="120" required placeholder="e.g. Maintenance supplies" value="${esc(s.title)}"></label><div class="field-row"><label>Customer<input value="Acme Facilities Pte Ltd" readonly></label><label>Recipient name<input name="recipient" required maxlength="120" placeholder="Purchasing contact" value="${esc(s.recipient)}"></label></div><label>Enquiry text<textarea name="text" required maxlength="20000" placeholder="50 EL-MCB-1P16&#10;20 BX-IP65-2015-A">${esc(s.text)}</textarea></label><label class="check"><input name="customer_confirmed" type="checkbox" required>I confirm the enquiry is for the synthetic Acme Facilities account, SGD, Jurong delivery on 19 Sep 2026.</label></div><div id="form-error" class="error" role="alert"></div><div class="dialog-footer"><button type="button" data-action="close-dialog">Cancel</button><button type="submit" class="primary">${icon('arrow-right')}Create enquiry</button></div></form>`; if(!dialog.open)dialog.showModal(); icons(); }
function readLines(){ return [...document.querySelectorAll('.line-item')].map(el=>{const old=current().lines[Number(el.dataset.line)];const values=Object.fromEntries([...el.querySelectorAll('[data-field]')].map(input=>[input.dataset.field,input.value]));return {...old,...values,sku:values.sku||null,qty:values.qty?Number(values.qty):null};}); }
async function mutate(payload){ const updated=await api(`/api/cases/${current().id}`,'PATCH',{revision:current().revision,...payload});replaceCase(updated);return updated; }

document.addEventListener('click',async event=>{
  const button=event.target.closest('[data-action]');if(!button||button.disabled||state.busy)return;
  const action=button.dataset.action;
  try{
    if(action==='new'||action==='sample'){showNew(action==='sample'?Number(button.dataset.index):undefined);return;}
    if(action==='preset'){showNew(Number(button.dataset.index));return;}
    if(action==='close-dialog'){button.closest('dialog').close();return;}
    if(action==='nav'){if(!discard())return;state.page=button.dataset.page;render();return;}
    if(action==='filter'||action==='queue'){state.filter=button.dataset.filter;state.page='inbox';render();return;}
    if(action==='open'){if(!discard())return;state.selected=button.dataset.id;state.page='case';state.tab='resolve';render();return;}
    if(action==='tab'){if(!discard())return;state.tab=button.dataset.tab;render();return;}
    if(action==='history'){await showHistory();return;}
    if(action==='download'){const response=await fetch(`/api/cases/${current().id}/${button.dataset.format}`,{headers:{'X-Demo-Actor':state.actor}});if(!response.ok){const data=await response.json();throw new Error(data.error);}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${current().id}-r${current().revision}.${button.dataset.format==='pdf'?'pdf':'txt'}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
    state.busy=true;
    if(action==='request-approvals'){replaceCase(await api(`/api/cases/${current().id}/request-approvals`,'POST',{revision:current().revision}));toast('Demo approvals requested.');}
    if(action==='decision'){const reason=$('#decision-reason').value.trim();if(!reason)throw new Error('Enter a decision reason.');replaceCase(await api(`/api/cases/${current().id}/decision`,'POST',{revision:current().revision,decision:button.dataset.decision,reason}));toast('Demo decision recorded.');}
    if(action==='save-lines'){await mutate({lines:readLines()});state.tab='price';toast('Lines confirmed. Pricing recalculated.');}
    if(action==='add-line'){const lines=readLines();lines.push({sku:null,qty:1,uom:'EA',discretionary_percent:'0',source:'Manually added line',question:'Select a catalogue product.'});await mutate({lines});}
    if(action==='remove-line'){const lines=readLines();lines.splice(Number(button.dataset.index),1);await mutate({lines});}
    if(action==='save-recipient'){await mutate({recipient:$('#recipient').value});toast('Recipient updated.');}
    if(action==='consent'){await mutate({delivery_accepted:$('#delivery-consent').checked});toast('Delivery decision recorded.');}
    if(action==='review'){replaceCase(await api(`/api/cases/${current().id}/review`,'POST',{revision:current().revision}));toast('Revision reviewed. Nothing has been sent.');}
    if(action==='delete'){if(!confirm('Delete this local case and its history?'))return;await api(`/api/cases/${current().id}`,'DELETE',{revision:current().revision});state.cases=state.cases.filter(c=>c.id!==state.selected);state.page='inbox';state.selected=null;}
    if(action==='refresh')state.cases=(await api('/api/cases')).cases;
    render();
  }catch(error){toast(error.message);}finally{state.busy=false;}
});
document.addEventListener('input',event=>{if(event.target.id==='search'){state.search=event.target.value;$('#case-table').innerHTML=caseTable();icons();}if(event.target.closest('.line-item'))state.dirty=true;});
document.addEventListener('change',event=>{if(event.target.matches('[data-field="sku"]')){const product=state.products.find(p=>p.sku===event.target.value);if(product)event.target.closest('.line-item').querySelector('[data-field="uom"]').value=product.uom;}});
document.addEventListener('submit',async event=>{if(event.target.id!=='new-form')return;event.preventDefault();if(state.busy)return;state.busy=true;const form=event.target,submit=form.querySelector('[type="submit"]');submit.disabled=true;try{const values=Object.fromEntries(new FormData(form));values.customer_confirmed=values.customer_confirmed==='on';const item=await api('/api/cases','POST',values);replaceCase(item);state.selected=item.id;state.page='case';state.tab='resolve';$('#enquiry-dialog').close();render();toast('Enquiry created.');}catch(error){$('#form-error').textContent=error.message;}finally{submit.disabled=false;state.busy=false;}});
window.addEventListener('beforeunload',event=>{if(state.dirty){event.preventDefault();event.returnValue='';}});
document.addEventListener('change',async event=>{
  if(event.target.id!=='persona')return;
  const previous=state.actor;
  if(!discard()){event.target.value=previous;return;}
  state.actor=event.target.value;
  sessionStorage.setItem('qf-demo-actor',state.actor);
  try{state.cases=(await api('/api/cases')).cases;render();toast('Demo persona changed.');}
  catch(error){state.actor=previous;sessionStorage.setItem('qf-demo-actor',previous);render();toast(error.message);}
});
async function start(){try{const [cases,catalogue,personas]=await Promise.all([api('/api/cases'),api('/api/catalogue'),api('/api/personas').catch(()=>({actors:[{id:'admin',name:'Demo Administrator',role:'Sales Administrator'}],simulated:false}))]);state.cases=cases.cases;state.products=catalogue.products;state.actors=personas.actors;state.approvalEnabled=personas.simulated===true;if(!state.actors.some(a=>a.id===state.actor))state.actor='admin';render();}catch(error){$('#app').innerHTML=`<div class="loading"><h2>Could not open workspace</h2><p>${esc(error.message)}</p><button data-action="reload">Reload</button></div>`;document.querySelector('[data-action="reload"]').onclick=()=>location.reload();}}
start();
